"""DOCX report generator using python-docx."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from ice_9.core.campaign import get_campaign_progress
from ice_9.core.models import Campaign, Finding, Severity
from ice_9.db.store import Store

SEVERITY_COLORS = {
    Severity.CRITICAL: RGBColor(0xDC, 0x26, 0x26),  # Red
    Severity.HIGH: RGBColor(0xEA, 0x58, 0x0C),       # Orange
    Severity.MEDIUM: RGBColor(0xCA, 0x8A, 0x04),      # Yellow
    Severity.LOW: RGBColor(0x25, 0x63, 0xEB),          # Blue
    Severity.INFO: RGBColor(0x6B, 0x72, 0x80),         # Gray
}


class ReportGenerator:
    """Generates penetration test reports in DOCX format."""

    def __init__(self, store: Store) -> None:
        self.store = store

    def generate(
        self,
        campaign: Campaign,
        output_path: Path,
        executive_summary: str = "",
        attack_narrative: str = "",
    ) -> Path:
        """Generate a full pentest report."""
        doc = Document()
        self._set_styles(doc)

        # Title page
        self._add_title_page(doc, campaign)

        # Table of contents placeholder
        doc.add_page_break()
        doc.add_heading("Table of Contents", level=1)
        doc.add_paragraph(
            "[Generate Table of Contents in Word: "
            "References > Table of Contents]",
            style="Intense Quote",
        )

        # Executive Summary
        doc.add_page_break()
        doc.add_heading("1. Executive Summary", level=1)
        if executive_summary:
            doc.add_paragraph(executive_summary)
        else:
            self._add_default_exec_summary(doc, campaign)

        # Scope
        doc.add_heading("2. Scope & Methodology", level=1)
        self._add_scope_section(doc, campaign)

        # Findings Summary
        doc.add_heading("3. Findings Summary", level=1)
        findings = self.store.get_all_findings(campaign.id)
        self._add_findings_summary(doc, findings)

        # Detailed Findings
        doc.add_heading("4. Detailed Findings", level=1)
        self._add_detailed_findings(doc, findings)

        # Attack Narrative
        if attack_narrative:
            doc.add_heading("5. Attack Narrative", level=1)
            doc.add_paragraph(attack_narrative)

        # Remediation Roadmap
        doc.add_heading("6. Remediation Roadmap", level=1)
        self._add_remediation_roadmap(doc, findings)

        # Appendix
        doc.add_heading("Appendix A: Methodology", level=1)
        self._add_methodology(doc, campaign)

        # Save
        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(output_path))
        return output_path

    def _set_styles(self, doc: Document) -> None:
        """Configure document styles."""
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(11)

        for i in range(1, 4):
            heading = doc.styles[f"Heading {i}"]
            heading.font.color.rgb = RGBColor(0xB9, 0x1C, 0x1C)  # Dark red

    def _add_title_page(self, doc: Document, campaign: Campaign) -> None:
        """Add the report title page."""
        for _ in range(6):
            doc.add_paragraph()

        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.add_run("PENETRATION TEST REPORT")
        run.bold = True
        run.font.size = Pt(28)
        run.font.color.rgb = RGBColor(0xB9, 0x1C, 0x1C)

        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(campaign.name)
        run.font.size = Pt(18)

        doc.add_paragraph()

        # Meta info
        meta = doc.add_paragraph()
        meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta.add_run(f"Client: {campaign.client or 'N/A'}\n").bold = True
        meta.add_run(f"Lead: {campaign.lead or 'N/A'}\n")
        meta.add_run(f"Date: {datetime.now(timezone.utc).strftime('%B %d, %Y')}\n")
        meta.add_run("Classification: CONFIDENTIAL\n").bold = True

        for _ in range(4):
            doc.add_paragraph()

        footer = doc.add_paragraph()
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer.add_run("Generated by ice_9")
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)

    def _add_default_exec_summary(self, doc: Document, campaign: Campaign) -> None:
        """Add a template executive summary."""
        progress = get_campaign_progress(campaign)
        findings = self.store.get_all_findings(campaign.id)

        severity_counts = {}
        for f in findings:
            severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

        doc.add_paragraph(
            f"A penetration test was conducted against the defined scope "
            f"for {campaign.client or campaign.name}. The assessment identified "
            f"{len(findings)} finding(s) across {progress['completed']} completed "
            f"phases of testing."
        )

        if severity_counts:
            doc.add_paragraph("Findings breakdown by severity:")
            for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
                count = severity_counts.get(sev, 0)
                if count:
                    doc.add_paragraph(f"  {sev.value.upper()}: {count}", style="List Bullet")

    def _add_scope_section(self, doc: Document, campaign: Campaign) -> None:
        """Add scope and methodology section."""
        roe = campaign.rules_of_engagement

        doc.add_heading("2.1 Scope", level=2)
        if roe.scope:
            doc.add_paragraph("The following targets were in scope:")
            for target in roe.scope:
                doc.add_paragraph(target, style="List Bullet")
        else:
            doc.add_paragraph("No explicit scope defined.")

        if roe.exclusions:
            doc.add_heading("2.2 Exclusions", level=2)
            for exc in roe.exclusions:
                doc.add_paragraph(exc, style="List Bullet")

        if roe.testing_window:
            doc.add_heading("2.3 Testing Window", level=2)
            doc.add_paragraph(roe.testing_window)

    def _add_findings_summary(self, doc: Document, findings: list[Finding]) -> None:
        """Add findings summary table."""
        if not findings:
            doc.add_paragraph("No findings were identified during this assessment.")
            return

        table = doc.add_table(rows=1, cols=4)
        table.style = "Light Grid Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        headers = table.rows[0].cells
        headers[0].text = "ID"
        headers[1].text = "Severity"
        headers[2].text = "Title"
        headers[3].text = "CVSS"

        for f in findings:
            row = table.add_row().cells
            row[0].text = f.id[:8]
            row[1].text = f.severity.value.upper()
            row[2].text = f.title
            row[3].text = f"{f.cvss:.1f}" if f.cvss else "-"

            # Color the severity cell
            sev_color = SEVERITY_COLORS.get(f.severity)
            if sev_color:
                for paragraph in row[1].paragraphs:
                    for run in paragraph.runs:
                        run.font.color.rgb = sev_color
                        run.bold = True

    def _add_detailed_findings(self, doc: Document, findings: list[Finding]) -> None:
        """Add detailed finding sections."""
        if not findings:
            doc.add_paragraph("No findings to detail.")
            return

        # Sort by severity
        severity_order = {
            Severity.CRITICAL: 0, Severity.HIGH: 1, Severity.MEDIUM: 2,
            Severity.LOW: 3, Severity.INFO: 4,
        }
        sorted_findings = sorted(findings, key=lambda f: severity_order.get(f.severity, 5))

        for i, f in enumerate(sorted_findings, 1):
            doc.add_heading(f"4.{i} {f.title}", level=2)

            # Severity badge
            p = doc.add_paragraph()
            run = p.add_run(f"Severity: {f.severity.value.upper()}")
            run.bold = True
            sev_color = SEVERITY_COLORS.get(f.severity)
            if sev_color:
                run.font.color.rgb = sev_color

            if f.cvss:
                p.add_run(f"  |  CVSS: {f.cvss:.1f}")

            if f.cve_ids:
                p.add_run(f"  |  CVEs: {', '.join(f.cve_ids)}")

            if f.att_ck_ids:
                p.add_run(f"  |  ATT&CK: {', '.join(f.att_ck_ids)}")

            # Description
            if f.description:
                doc.add_heading("Description", level=3)
                doc.add_paragraph(f.description)

            # Remediation
            if f.remediation:
                doc.add_heading("Remediation", level=3)
                doc.add_paragraph(f.remediation)

            # Evidence
            if f.evidence:
                doc.add_heading("Evidence", level=3)
                for ev in f.evidence:
                    doc.add_paragraph(
                        f"{ev.description or 'Evidence'}: {ev.file_path or 'N/A'} "
                        f"(SHA256: {ev.sha256[:16]}...)" if ev.sha256 else "",
                        style="List Bullet",
                    )

    def _add_remediation_roadmap(self, doc: Document, findings: list[Finding]) -> None:
        """Add prioritized remediation roadmap."""
        if not findings:
            doc.add_paragraph("No remediation actions required.")
            return

        doc.add_paragraph(
            "The following remediation actions are recommended, "
            "prioritized by severity:"
        )

        priority_map = {
            Severity.CRITICAL: "Immediate (24-48 hours)",
            Severity.HIGH: "Short-term (1-2 weeks)",
            Severity.MEDIUM: "Medium-term (1-3 months)",
            Severity.LOW: "Long-term (next quarter)",
            Severity.INFO: "Informational",
        }

        for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
            sev_findings = [f for f in findings if f.severity == sev and f.remediation]
            if not sev_findings:
                continue

            doc.add_heading(f"Priority: {priority_map[sev]}", level=2)
            for f in sev_findings:
                doc.add_paragraph(f"{f.title}", style="List Bullet")
                if f.remediation:
                    doc.add_paragraph(f"  → {f.remediation}", style="List Bullet 2")

    def _add_methodology(self, doc: Document, campaign: Campaign) -> None:
        """Add methodology appendix."""
        doc.add_paragraph(
            "This assessment followed the MITRE ATT&CK framework, "
            "covering the following tactics:"
        )

        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        headers = table.rows[0].cells
        headers[0].text = "ATT&CK ID"
        headers[1].text = "Tactic"
        headers[2].text = "Status"

        for phase in campaign.phases:
            row = table.add_row().cells
            row[0].text = phase.phase_type.value
            row[1].text = phase.name
            row[2].text = phase.status.value
